<?php
/**
 */

namespace execut\images\crudFields;

use execut\crudFields\fields\HasOneSelect2;
use execut\files\models\File;
use yii\helpers\Html;
use yii\helpers\UnsetArrayValue;
use execut\images\Attacher;

class Plugin extends \execut\crudFields\Plugin
{
    public $previewDataAttribute = 'img_100';
    public $moduleId = 'images';
    public function getFields() {
//        $thumbAttributes = array_keys(\yii::$app->getModule('images')->getSizes());
//        $result = [];
//        foreach ($thumbAttributes as $thumbAttribute) {
//            $result[$thumbAttribute] = [
//                'attribute' => $thumbAttribute,
//            ];
//        }
//
//        return $result;
//

        $value = function ($row) {
            $module = \yii::$app->getModule($this->moduleId);
            $extensionAttribute = $module->extensionAttribute;
            $filesModule = $module->getFilesModule();
            $sizes = $module->getSizes();
            $formats = $filesModule->getFormats();
            foreach ($sizes as $sizeName => $size) {
                if (!empty($size['width'])) {
                    $width = $size['width'];
                } else {
                    $width = '';
                }

                if (!empty($size['height'])) {
                    $height = $size['height'];
                } else {
                    $height = '';
                }

                $links[] = Html::a($width . 'x' . $height . ' ' . $row->$extensionAttribute, [
                    '/' . $module->filesModuleId . '/frontend',
                    'id' => $row->id,
                    'dataAttribute' => $sizeName,
                ]);
                foreach ($formats as $extension => $format) {
                    $links[] = Html::a($width . 'x' . $height . ' ' . $extension, [
                        '/' . $module->filesModuleId . '/frontend',
                        'id' => $row->id,
                        'dataAttribute' => $row->getDataAttributeNameForFormat($sizeName, $extension),
                    ]);
                }
            }

            return Html::a(Html::img(['/' . $module->filesModuleId . '/frontend/index', 'id' => $row->id, 'extension' => strtolower($row->$extensionAttribute), 'dataAttribute' => $this->previewDataAttribute]), [
                '/' . $module->filesModuleId . '/frontend/index',
                'id' => $row->id,
                'extension' => strtolower($row->$extensionAttribute),
            ]) . '<div>' . implode('<br>', $links) . '</div>';
        };
        return [
            'preview' => [
                'module' => 'images',
                'attribute' => 'preview',
                'scope' => false,
                'field' => [
                    'format' => 'raw',
                    'displayOnly' => true,
                    'value' => function ($form, $widget) use ($value) {
                        return $value($widget->model);
                    },
                ],
                'column' => [
                    'filter' => false,
                    'format' => 'raw',
                    'value' => $value,
                ],
            ],
            [
                'attribute' => 'width',
                'displayOnly' => true,
                'module' => 'images',
            ],
            [
                'attribute' => 'height',
                'displayOnly' => true,
                'module' => 'images',
            ],
//            [
//                'attribute' => 'alt',
//            ],
//            [
//                'attribute' => 'title',
//            ],
        ];
    }

    public function attach()
    {
        parent::attach(); // TODO: Change the autogenerated stub
        $this->attachToModules();
    }



    protected function attachToModules() {
        $module = \yii::$app->getModule($this->moduleId);
        $filesModule = $module->getFilesModule();
        $sizes = $module->getSizes();
        $formats = $filesModule->getFormats();

        $attacher = new Attacher([
            'tables' => [
                $this->owner->tableName(),
            ],
            'sizes' => $sizes,
            'formats' => array_keys($formats),
        ]);

        $attacher->safeUp();
    }
}